# Generated by Django 3.1.4 on 2020-12-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='coursePic',
            field=models.CharField(default='http://', max_length=500),
        ),
        migrations.AddField(
            model_name='courses',
            name='coursePrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='courses',
            name='courseRate',
            field=models.FloatField(default=0.0),
        ),
    ]
