# Generated by Django 3.1.4 on 2020-12-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrecord',
            old_name='receiveId',
            new_name='receiveName',
        ),
        migrations.RenameField(
            model_name='chatrecord',
            old_name='sendId',
            new_name='sendName',
        ),
    ]
