# Generated by Django 3.1.4 on 2020-12-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=200)),
                ('schoolAddress', models.CharField(max_length=300)),
                ('schoolType', models.CharField(max_length=150)),
                ('schoolDescription', models.TextField()),
                ('schoolLogo', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.CharField(max_length=100)),
                ('studentName', models.CharField(max_length=200)),
                ('studentSex', models.CharField(max_length=20)),
                ('schoolName', models.CharField(max_length=200)),
                ('studentImage', models.CharField(max_length=400)),
            ],
        ),
    ]
