# Generated by Django 3.1.4 on 2020-12-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_selfintroduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('homeworkName', models.CharField(max_length=100)),
                ('ddlTime', models.DateTimeField()),
            ],
        ),
    ]
