# Generated by Django 3.1.4 on 2020-12-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.CharField(max_length=200)),
                ('teacherName', models.CharField(max_length=100)),
                ('teacherSex', models.CharField(max_length=20)),
                ('teacherPosition', models.CharField(max_length=300)),
                ('schoolName', models.CharField(max_length=100)),
                ('broadcastRoomId', models.CharField(max_length=100)),
            ],
        ),
    ]
