# Generated by Django 3.1.4 on 2020-12-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='teach_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
