# Generated by Django 3.1.4 on 2020-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teachers_teach_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='picUrl',
            field=models.CharField(default='http://', max_length=500),
        ),
        migrations.AddField(
            model_name='teachers',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
