# Generated by Django 3.1.4 on 2020-12-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20201209_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach_list',
            fields=[
                ('teacherId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('teacherName', models.CharField(max_length=100)),
                ('you_can_learn', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='teachers',
            name='brief_introduction',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='teachers',
            name='letters',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
