# Generated by Django 3.1.4 on 2020-12-13 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20201213_0938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teach_list',
        ),
    ]
