# Generated by Django 3.1.4 on 2020-12-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teach_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teach_list',
            new_name='Learn_list',
        ),
    ]
