# Generated by Django 3.1.4 on 2020-12-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20201213_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn_list',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
