# Generated by Django 3.1.4 on 2020-12-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20201213_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teachers',
            name='student_num',
            field=models.IntegerField(default=0),
        ),
    ]
