# Generated by Django 3.1.4 on 2020-12-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20201213_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='icon',
            field=models.CharField(default='https://', max_length=500),
        ),
    ]
